import { MOCK_ADMIN_DASHBOARD } from "./admin";
import { getMockFacultyDashboard } from "./faculty";
import { getMockAssignments, getMockAttendance } from "./student";
import { getAssignmentsForFaculty } from "./assignments";
import { subjectName } from "@/services/schedule";
import { formatShortDate } from "@/utils/date";
import { DEMO_FACULTY_NAME, DEMO_TODAY, DEMO_NOW } from "@/constants/demo";
import type { AuthUser } from "@/types/auth";
import type {
  ActivityNotificationInput,
  AppNotification,
  NotificationAudience,
} from "@/types/notification";
import { effectiveScheduleForDate } from "@/services/schedule";

/**
 * Notifications are generated from the same mock sources the dashboard reads
 * (attendance, assignments, schedule overrides), so they can never contradict
 * the views they accompany. Each role sees only its own audience-scoped items —
 * e.g. a Microprocessor attendance alert belongs to the student (and its
 * faculty), never to an unrelated Python Lab faculty account.
 */

/* ------------------------------------------------------------------ */
/* Runtime activity notifications                                      */
/* ------------------------------------------------------------------ */

interface ActivityEntry extends AppNotification {
  audience: NotificationAudience;
  dedupeKey?: string;
}

/**
 * Notifications generated by real mutations during the demo session
 * (assignment published, submission received, schedule changed, notice/event
 * published, material uploaded, grade issued). Each carries an audience so a
 * students-only event never leaks into the faculty feed. Pushing an entry
 * with the same dedupe key refreshes the existing item instead of duplicating.
 */
const ACTIVITY: ActivityEntry[] = [];

export function pushActivityNotification(input: ActivityNotificationInput): void {
  const timestamp = DEMO_NOW.toISOString();
  const existingIndex = ACTIVITY.findIndex((item) => {
    if (input.dedupeKey) return item.dedupeKey === input.dedupeKey;
    return item.title === input.title && item.body === input.body;
  });
  if (existingIndex !== -1) {
    ACTIVITY[existingIndex] = {
      ...ACTIVITY[existingIndex],
      timestamp,
      read: false,
    };
    return;
  }
  ACTIVITY.unshift({
    id: `act-${Date.now().toString(36)}`,
    category: input.category,
    title: input.title,
    body: input.body,
    audience: input.audience ?? "all",
    priority: input.priority,
    subjectCode: input.subjectCode,
    dedupeKey: input.dedupeKey,
    timestamp,
    read: false,
  });
}

function activityForUser(user: AuthUser): AppNotification[] {
  return ACTIVITY.filter((item) => {
    if (item.audience === "all") return true;
    if (item.audience === "students") return user.role === "student";
    return item.audience === user.role;
  }).map((item) => ({ ...item }));
}

/* ------------------------------------------------------------------ */
/* Static institutional + role-derived notifications                  */
/* ------------------------------------------------------------------ */

/** Institutional items shared by every role. */
const COMMON: AppNotification[] = [
  {
    id: "com-ia1",
    category: "academic",
    title: "Internal Assessment schedule published",
    body: "Semester 3 internal assessment timetable is now available.",
    timestamp: "2026-08-14T09:30:00Z",
    read: false,
    priority: "high",
  },
  {
    id: "com-sih",
    category: "notice",
    title: "SIH 2026 internal round registrations open",
    body: "Registrations close Sunday. Teams of up to six, ideas pitched on Aug 18.",
    timestamp: "2026-08-12T11:00:00Z",
    read: false,
    priority: "normal",
  },
  {
    id: "com-sports",
    category: "event",
    title: "Sports trials — cricket & athletics",
    body: "Trials begin at 4:00 PM on the main ground.",
    timestamp: "2026-08-11T16:45:00Z",
    read: true,
    priority: "low",
  },
];

function studentNotifications(): AppNotification[] {
  const items: AppNotification[] = [];

  for (const subject of getMockAttendance()) {
    if (subject.status === "critical") {
      items.push({
        id: `att-critical-${subject.code}`,
        category: "attendance",
        title: `${subject.subject} attendance below threshold`,
        body: `${subject.subject} attendance has dropped to ${subject.percent}%, below the ${subject.threshold}% threshold.`,
        timestamp: "2026-08-14T08:00:00Z",
        read: false,
        priority: "high",
        subjectCode: subject.code,
      });
    } else if (subject.status === "warning") {
      items.push({
        id: `att-warning-${subject.code}`,
        category: "attendance",
        title: `${subject.subject} attendance needs attention`,
        body: `${subject.subject} attendance is at ${subject.percent}% and approaching the ${subject.threshold}% threshold.`,
        timestamp: "2026-08-14T08:00:00Z",
        read: false,
        priority: "normal",
        subjectCode: subject.code,
      });
    }
  }

  for (const assignment of getMockAssignments()) {
    if (assignment.status === "late") {
      items.push({
        id: `asg-late-${assignment.id}`,
        category: "assignment",
        title: `${assignment.subject} — submission overdue`,
        body: `"${assignment.title}" is past its due date. Submit at the earliest.`,
        timestamp: "2026-08-14T09:00:00Z",
        read: false,
        priority: "high",
        subjectCode: assignment.code,
      });
    } else if (assignment.status === "pending" && assignment.priority === "high") {
      items.push({
        id: `asg-${assignment.id}`,
        category: "assignment",
        title: `${assignment.title} due soon`,
        body: `Submit your ${assignment.subject} file before the deadline.`,
        timestamp: "2026-08-13T14:15:00Z",
        read: false,
        priority: "normal",
        subjectCode: assignment.code,
      });
    }
  }

  for (const slot of effectiveScheduleForDate(DEMO_TODAY)) {
    const adjustment = slot.adjustment;
    if (!adjustment) continue;
    switch (adjustment.kind) {
      case "cancelled":
        items.push({
          id: `sched-cancelled-${slot.code}`,
          category: "academic",
          title: `${slot.subject} — class cancelled`,
          body: `Your ${slot.start} ${slot.subject} class has been cancelled.`,
          timestamp: "2026-08-15T07:00:00Z",
          read: false,
          priority: "high",
          subjectCode: slot.code,
        });
        break;
      case "rescheduled": {
        const source = adjustment.sourceDate
          ? `${formatShortDate(adjustment.sourceDate)} ${adjustment.movedFromTime ?? ""}`.trim()
          : adjustment.movedFromTime;
        items.push({
          id: `sched-rescheduled-${slot.code}`,
          category: "academic",
          title: `${slot.subject} — rescheduled`,
          body: `Moved from ${source} to ${slot.start} today.`,
          timestamp: "2026-08-15T07:00:00Z",
          read: false,
          priority: "high",
          subjectCode: slot.code,
        });
        break;
      }
      case "room_changed":
        items.push({
          id: `sched-room-${slot.code}`,
          category: "academic",
          title: `${slot.subject} — room changed`,
          body: `Today's ${slot.start} ${slot.subject} is now in ${slot.room}.`,
          timestamp: "2026-08-15T07:00:00Z",
          read: false,
          priority: "normal",
          subjectCode: slot.code,
        });
        break;
      case "faculty_changed":
        items.push({
          id: `sched-faculty-${slot.code}`,
          category: "academic",
          title: `${slot.subject} — faculty changed`,
          body: `Today's ${slot.start} ${slot.subject} is now taken by ${slot.faculty}.`,
          timestamp: "2026-08-15T07:00:00Z",
          read: false,
          priority: "normal",
          subjectCode: slot.code,
        });
        break;
      case "extra":
        items.push({
          id: `sched-extra-${slot.code}`,
          category: "academic",
          title: `${slot.subject} — additional lecture`,
          body: `An extra session has been added at ${slot.start} in ${slot.room}.`,
          timestamp: "2026-08-15T07:00:00Z",
          read: false,
          priority: "normal",
          subjectCode: slot.code,
        });
        break;
      case "swapped":
        items.push({
          id: `sched-swapped-${slot.code}`,
          category: "academic",
          title: `${slot.subject} — time swapped`,
          body: `Swapped with ${subjectName(adjustment.swappedWithCode ?? "")} today.`,
          timestamp: "2026-08-15T07:00:00Z",
          read: false,
          priority: "normal",
          subjectCode: slot.code,
        });
        break;
    }
  }

  return items;
}

function facultyNotifications(): AppNotification[] {
  const items: AppNotification[] = [];
  const dashboard = getMockFacultyDashboard();

  for (const submission of dashboard.submissions) {
    items.push({
      id: `fac-sub-${submission.id}`,
      category: "assignment",
      title: `${submission.subject} — pending submissions`,
      body: `${submission.pending} of ${submission.total} submissions for "${submission.assignmentTitle}" still need review.`,
      timestamp: "2026-08-14T16:00:00Z",
      read: false,
      priority: submission.pending > 3 ? "high" : "normal",
      subjectCode: submission.code,
    });
  }

  const unmarked = dashboard.classes.filter((c) => !c.attendanceMarked);
  if (unmarked.length > 0) {
    items.push({
      id: "fac-att-mark",
      category: "attendance",
      title: "Attendance not yet marked",
      body: `You have ${unmarked.length} class session${unmarked.length === 1 ? "" : "s"} today with attendance to record.`,
      timestamp: "2026-08-15T07:30:00Z",
      read: false,
      priority: "normal",
    });
  }

  for (const assignment of getAssignmentsForFaculty(DEMO_FACULTY_NAME)) {
    const daysLeft = Math.ceil(
      (new Date(assignment.dueDate).getTime() - DEMO_NOW.getTime()) / 86_400_000,
    );
    if (daysLeft <= 2) {
      items.push({
        id: `fac-asg-due-${assignment.id}`,
        category: "assignment",
        title: `"${assignment.title}" closes soon`,
        body: `Submissions close in ${daysLeft <= 0 ? "less than a day" : `${daysLeft} day${daysLeft === 1 ? "" : "s"}`}.`,
        timestamp: "2026-08-14T12:00:00Z",
        read: false,
        priority: "normal",
        subjectCode: assignment.code,
      });
    }
  }

  for (const atRisk of dashboard.atRisk.slice(0, 3)) {
    items.push({
      id: `fac-risk-${atRisk.code}-${atRisk.student.id}`,
      category: "attendance",
      title: `${atRisk.student.name} — attendance below threshold`,
      body: `${atRisk.subject} attendance is ${atRisk.percent}%, under the ${atRisk.threshold}% mark.`,
      timestamp: "2026-08-14T14:00:00Z",
      read: false,
      priority: "normal",
      subjectCode: atRisk.code,
    });
  }

  items.push({
    id: "fac-dl-ia1",
    category: "academic",
    title: "IA 1 marks due for departmental review",
    body: "IA 1 marks must reach the department office by Aug 18.",
    timestamp: "2026-08-14T10:00:00Z",
    read: false,
    priority: "normal",
  });

  return items;
}

function adminNotifications(): AppNotification[] {
  const pending = MOCK_ADMIN_DASHBOARD.stats.pendingApprovals;
  return [
    {
      id: "adm-pending",
      category: "system",
      title: "Approvals awaiting review",
      body: `${pending} requests are pending in the admin console.`,
      timestamp: "2026-08-15T08:15:00Z",
      read: false,
      priority: "high",
    },
    {
      id: "adm-attendance",
      category: "attendance",
      title: "Attendance report ready",
      body: "Yesterday's institute-wide attendance is available in reports.",
      timestamp: "2026-08-14T18:00:00Z",
      read: false,
      priority: "normal",
    },
  ];
}

function buildForUser(user: AuthUser): AppNotification[] {
  const activity = activityForUser(user);
  switch (user.role) {
    case "student":
      return [...activity, ...COMMON, ...studentNotifications()];
    case "faculty":
      return [...activity, ...COMMON, ...facultyNotifications()];
    case "admin":
      return [...activity, ...COMMON, ...adminNotifications()];
  }
}

/** Per-user read state (keyed by role:id) so switching roles is isolated. */
const readState = new Map<string, Set<string>>();

function readKey(user: AuthUser): string {
  return `${user.role}:${user.id}`;
}

function applyReadState(user: AuthUser, items: AppNotification[]): AppNotification[] {
  const readIds = readState.get(readKey(user));
  if (!readIds) return items;
  return items.map((item) =>
    readIds.has(item.id) ? { ...item, read: true } : item,
  );
}

export function getMockNotificationsForUser(user: AuthUser): AppNotification[] {
  const items = buildForUser(user)
    .slice()
    .sort((a, b) => b.timestamp.localeCompare(a.timestamp));
  return applyReadState(user, items);
}

export function markAllMockNotificationsRead(user: AuthUser): void {
  const readIds = readState.get(readKey(user)) ?? new Set<string>();
  for (const item of buildForUser(user)) {
    readIds.add(item.id);
  }
  readState.set(readKey(user), readIds);
}
